name: Be CI
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/be/**'
      - '.github/workflows/be-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/be/**'
      - '.github/workflows/be-ci.yml'
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./apps/be

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: apps/be/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm run test

    - name: Run coverage
      run: npm run coverage
      continue-on-error: true

    - name: Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.1
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./apps/be/coverage/lcov.info
        delete-old-comments: true