name: Eth Contract CI

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/nft-hub-eth/**'
      - '.github/workflows/eth-contract-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/nft-hub-eth/**'
      - '.github/workflows/eth-contract-ci.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  compile-and-test:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: ./contracts/nft-hub-eth

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: contracts/nft-hub-eth/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Compile contracts
      run: npm run compile

    - name: Run tests
      run: npm run test

    - name: Run coverage
      run: npm run coverage
      continue-on-error: true

    - name: Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.1
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./contracts/nft-hub-eth/coverage/lcov.info
        delete-old-comments: true