name: Fe CI
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/fe/**'
      - '.github/workflows/fe-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/fe/**'
      - '.github/workflows/fe-ci.yml'
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./apps/fe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: apps/fe/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm run test